name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Preparar o ambiente
        run: |
          echo "Simulando a preparação do ambiente de testes..."

      - name: Rodar os testes (CI)
        run: |
          echo "Etapa de CI: Testes rodando... (ok)"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - name: Fazer a entrega (CD)
        run: |
          echo "Etapa de CD: Entrega concluída... (ok)"
